baseURL: 'https://florianformentini.fr'
languageCode: fr
defaultContentLanguage: fr

title: "Florian F."
theme: "toha"


# Manage languages - https://gohugo.io/content-management/multilingual/
languages:
  fr:
    languageName: Fr
    weight: 1
  en:
    languageName: En
    weight: 2

# Enable global emoji support
enableEmoji: true

# markdown and other markup related configuration
markup:
  # Control TOC depth
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  # raw html in markdown files
  goldmark:
    renderer:
      unsafe: true

# At least HTML and JSON are required for the main HTML content and client-side JavaScript search
outputs:
  home:
  - HTML
  - JSON
  # - RSS

# Site parameters
params:
    # relative to assets folder
  background: "images/site/background.jpg"

  logo:
    # non-transparent navbar
    main: images/site/logo.png
    # initial transparent navbar
    inverted: images/site/logo.png  
    favicon: images/site/logo.png

  # enable / disable blog 
  enableBlogPost: true

  # Enable <Improve This Page> buton in posts
  # gitRepo: https://github.com/Flooow54/MyHugoPortfolio
  # gitBranch: main

  # Table of Contents in reading page
  enableTOC: true

  # newsletter configuration - implemented for Mailchimp only
  newsletter:
    enable: false
    # provider: mailchimp
    # target URL for the subscription form
    # mailchimpURL: 

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5

  # Configure various features of this theme
  features:
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        # whatsapp: true
        # email: true

    # Enable & configure "Notes" features
    notes:
      enable: false

    # Enable comment feature.
    comment:
      enable: true
      disqus:
        shortName: florianf

    # Enable Analytics
    analytics:
      # CounterDev
      # counterDev:
      #   id: <your counterdev id>
      # GoatCounter
      # goatCounter:
      #   code: <your goat counter code>

    # Enable Support
    support:
      enabled: true
      kofi:
        user: florianformentini
        text: Tips
        textColor: '#f9fafc'
        backgroundColor: '#248aaa'


  # Show tags under the post title
  enableTags: true

  # If you want to use different country flag for a language, specify them here.
  flagOverwrites:
  - languageCode: en
    countryCode: us

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true


    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true


